
export const LOGIN = 'MEMBER_LOGIN'
export const REFRESH_TOKEN = 'MEMBER_REFRESH_TOKEN'
export const ACCESS_TOKEN_EXPIRED = 'MEMBER_ACCESS_TOKEN_EXPIRED'
export const REFRESH_TOKEN_EXPIRED = 'MEMBER_REFRESH_TOKEN_EXPIRED'
export const LOGIN_SUCCESS = 'MEMBER_LOGIN_SUCCESS'
export const LOGIN_FAIL = 'MEMBER_LOGIN_FAIL'
export const LOGOUT = 'MEMBER_LOGOUT'

export const USER_PROFILE = 'MEMBER_USER_PROFILE'
export const PRODUCT_LIST = 'PRODUCT_LIST'
