export const GLOBAL_WELCOME_HAS_SHOW = 'GLOBAL_WELCOME_HAS_SHOW'
export const GLOBAL_INITIAL = 'GLOBAL_INITIAL'
export const GLOBAL_VERSION_UPDATE = 'GLOBAL_VERSION_UPDATE'
export const GLOBAL_VERSION_UPDATE_FINISH = 'GLOBAL_VERSION_UPDATE_FINISH'
